version: "3.9"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend
    command:
      - python api.py
  db:
    hostname: db
    image: postgres:14.7-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5456:5456
    environment:
      - POSTGRES_USER=zhanat
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=test
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge

