"""Create Table emp and dep

Revision ID: 0fbb3332aee3
Revises: 1076da284858
Create Date: 2023-06-21 19:35:08.159211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbb3332aee3'
down_revision = '1076da284858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departament', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('employee', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('employee', sa.Column('surname', sa.String(length=50), nullable=False))
    op.add_column('employee', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('employee', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('age', sa.SmallInteger(), nullable=True))
    op.add_column('employee', sa.Column('departament_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_employee_surname'), 'employee', ['surname'], unique=False)
    op.create_foreign_key(None, 'employee', 'departament', ['departament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_index(op.f('ix_employee_surname'), table_name='employee')
    op.drop_column('employee', 'departament_id')
    op.drop_column('employee', 'age')
    op.drop_column('employee', 'salary')
    op.drop_column('employee', 'position')
    op.drop_column('employee', 'surname')
    op.drop_column('employee', 'username')
    op.drop_column('departament', 'title')
    # ### end Alembic commands ###
