"""Create Table auth

Revision ID: 91cce0d29ad1
Revises: 0fbb3332aee3
Create Date: 2023-06-21 21:10:01.457029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91cce0d29ad1'
down_revision = '0fbb3332aee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
